name: Compilar LineageOS GSI Do Zero

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Limpeza Ultra Rapida de Disco Nativa
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/swift
        sudo apt-get clean

    - name: Instalar Dependencias e Compiladores do Ubuntu
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y git openjdk-17-jdk python3 repo make bc bison curl flex g++ gperf libncurses5-dev libssl-dev libxml2-utils unzip zip zlib1g-dev zlib1g-dev:i386 ccache lzop rsync

    - name: Configurar o Google Repo e Identidade Git
      run: |
        mkdir -p ~/bin
        curl https://googleapis.com > ~/bin/repo
        chmod a+x ~/bin/repo
        git config --global user.name "Brayan"
        git config --global user.email "brayan@example.com"

    - name: Baixar Codigo Fonte do LineageOS 19.1
      run: |
        export PATH=~/bin:$PATH
        mkdir -p ~/lineage-gsi
        cd ~/lineage-gsi
        # LINK OFICIAL CORRIGIDO E BRANQUADO PARA LINEAGE-19.1
        repo init -u https://github.com -b lineage-19.1 --depth=1 --git-lfs --no-clone-bundle
        repo sync -c -j4 --no-tags --no-clone-bundle

    - name: Iniciar Compilacao Real da GSI
      run: |
        export PATH=~/bin:$PATH
        cd ~/lineage-gsi
        source build/envsetup.sh
        lunch lineage_a64_ab-userdebug || lunch aosp_a64_ab-userdebug
        export CCACHE_DISABLE=1
        export ALLOW_MISSING_DEPENDENCIES=true
        export TEMPORARY_DISABLE_PATH_RESTRICTIONS=1
        make systemimage -j$(nproc) ALLOW_MISSING_DEPENDENCIES=true

    - name: Compactar Imagem system.img Gerada
      run: |
        cd ~/lineage-gsi/out/target/product/* || true
        zip -r meu_android_do_zero.zip system.img

    - name: Disponibilizar Link para Download da sua GSI
      uses: actions/upload-artifact@v4
      with:
        name: GSI-Lineage-12-Do-Zero
        path: ~/lineage-gsi/out/target/product/*/*.zip
